tests: Fix exception handling in rdmacm test
This test uses multiprocessing but exceptions were not properly reported
from child processes to parent. Add a report mechanism from child to
parent process.
Change Popen object usage to check_output for safer code.
Change synchronization object between processes.

Before this patch:
[leonro@server ~]$ /images/leonro/src/rdma-core/build/bin/run_tests.py -k rdmacm
Process Process-1:
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/images/leonro/src/rdma-core/tests/rdmacm_utils.py", line 46, in passive_side
    server = CMResources(src=src_addr)
  File "/images/leonro/src/rdma-core/tests/base.py", line 178, in __init__
    self.cmid = CMID(creator=self.ai, qp_init_attr=self.qp_init_attr)
  File "cmid.pyx", line 133, in pyverbs.cmid.CMID.__cinit__
pyverbs.pyverbs_error.PyverbsRDMAError: Failed to create CM ID. Errno: 5, Input/output error
Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/images/leonro/src/rdma-core/tests/rdmacm_utils.py", line 18, in active_side
    client = CMResources(dst=dst_addr)
  File "/images/leonro/src/rdma-core/tests/base.py", line 178, in __init__
    self.cmid = CMID(creator=self.ai, qp_init_attr=self.qp_init_attr)
  File "cmid.pyx", line 133, in pyverbs.cmid.CMID.__cinit__
pyverbs.pyverbs_error.PyverbsRDMAError: Failed to create CM ID. Errno: 1, Operation not permitted
.
----------------------------------------------------------------------
Ran 1 test in 1.334s

OK

After this patch:
[leonro@server ~]$ /images/leonro/src/rdma-core/build/bin/run_tests.py -k rdmacm
E
======================================================================
ERROR: test_rdmacm_sync_traffic (tests.test_rdmacm.CMTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/images/leonro/src/rdma-core/tests/test_rdmacm.py", line 68, in test_rdmacm_sync_traffic
    raise PyverbsError(res)
pyverbs.pyverbs_error.PyverbsError: Caught exception in passive side process: pid 745
Exception message: Failed to create CM ID. Errno: 5, Input/output error

----------------------------------------------------------------------
Ran 1 test in 1.275s

FAILED (errors=1)

Fixes: 92c7cb50d545 ("tests: Add RDMACM synchronous traffic test")
Signed-off-by: Maxim Chicherin <maximc@mellanox.com>
Reviewed-by: Noa Osherovich <noaos@mellanox.com>
Signed-off-by: Leon Romanovsky <leonro@mellanox.com>