ocrdma: Fix uninit_use issues
[ Upstream commit 509cc96ece11bb78896ea5fdd46cf04c71139550 ]

Fix the following issues:
Error: UNINIT (CWE-457): [#def138] [important]
providers/ocrdma/ocrdma_main.c:118:2: var_decl: Declaring variable "resp" without initializer.
providers/ocrdma/ocrdma_main.c:132:2: uninit_use: Using uninitialized value "resp.dev_id".

Error: UNINIT (CWE-457): [#def140] [important]
providers/ocrdma/ocrdma_verbs.c:359:2: var_decl: Declaring variable "resp" without initializer.
providers/ocrdma/ocrdma_verbs.c:373:2: uninit_use: Using uninitialized value "resp.rq_dbid".

Error: UNINIT (CWE-457): [#def141] [important]
providers/ocrdma/ocrdma_verbs.c:469:2: var_decl: Declaring variable "resp" without initializer.
providers/ocrdma/ocrdma_verbs.c:504:2: uninit_use: Using uninitialized value "resp.qp_id".

Fixes: ede311583f51 ("Added libocrdma files")
Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Nicolas Morey <nmorey@suse.com>