tests: Skip test if QP type is not supported
Avoid the following failure when running the test_rdmacm_async_udp_traffic
test over the qedr provider, this is happening because UD QP is not
supported by the qedr provider.

======================================================================
ERROR: test_rdmacm_async_udp_traffic (tests.test_rdmacm.CMTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rdma-core/tests/test_rdmacm.py", line 57, in test_rdmacm_async_udp_traffic
    self.two_nodes_rdmacm_traffic(CMAsyncConnection, self.rdmacm_traffic,
  File "/home/rdma-core/tests/base.py", line 370, in two_nodes_rdmacm_traffic
    raise(res)
pyverbs.pyverbs_error.PyverbsRDMAError: Failed to Create QP. Errno: 95, Operation not supported

----------------------------------------------------------------------

Signed-off-by: Kamal Heib <kamalheib1@gmail.com>