providers/mana: Fix build after kernel-headers update renamed create_cq flags
Previous commit renamed the 'flags' field of 'struct mana_ib_create_cq'
to 'comp_mask' to match the upstream kernel uapi header.
This broke the build:

  ../providers/mana/cq.c: In function 'mana_create_cq':
  ../providers/mana/cq.c:168:9: error: 'struct mana_ib_create_cq' has
  no member named 'flags'
    cmd_drv->flags = flags;
           ^~

Update mana_create_cq() to write the local 'flags' bitmask into the
renamed 'comp_mask' field.

Signed-off-by: Selvin Xavier <selvin.xavier@broadcom.com>