libhns: Fix return value when creating unsupported CQ flags
[ Upstream commit 1dc4f7d6d9c63a76f85c958c0fe2c75345a8ea3f ]

Errno EVINAL has been returned when create CQ with unsupported flags
which caused a bunch of testcase to fail, e.g.

ERROR: test_create_cq_ex (tests.test_cqex.CQEXAPITest)
Test ibv_create_cq_ex()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test_cqex.py", line 117, in test_create_cq_ex
    raise ex
  File "./tests/test_cqex.py", line 113, in test_create_cq_ex
    cq_ex = CQEX(self.ctx, cq_init_attrs_ex)
  File "cq.pyx", line 329, in pyverbs.cq.CQEX.__init__
pyverbs.pyverbs_error.PyverbsRDMAError: Failed to create extended CQ. Errno: 22, Invalid argument

Fixes: 75c39c4d8bad ("libhns: Refactor cq creation flow")
Signed-off-by: Chengchang Tang <tangchengchang@huawei.com>
Signed-off-by: Haoyue Xu <xuhaoyue1@hisilicon.com>
Signed-off-by: Leon Romanovsky <leonro@nvidia.com>
Signed-off-by: Nicolas Morey <nmorey@suse.com>