srp_daemon: Increase the alignment for some of the packet structs
When these overlay the containing MAD's data_buffer the alignment is
at least 4 bytes. Tell the compiler about this so it can properly
compute the alignment of the internal umad_gid.

Otherwise it assumes the containing struct can be at any alignment
and clang 4.0 complains:

../srp_daemon/srp_handle_traps.c:738:9: error: taking address of packed member 'gid' of class or structure '_ntc_64_67' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
                                                 &notice_buffer->data_details.ntc_64_67.gid,
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Jason Gunthorpe <jgunthorpe@obsidianresearch.com>