ibtracert.c: fix RESOURCE_LEAK issues
[ Upstream commit 4ec6f085520555a8a593ce861e39dfea0de43d41 ]

Error: RESOURCE_LEAK (CWE-772):
rdma-core-29.0/infiniband-diags/ibtracert.c:545: alloc_fn: Storage is returned from allocation function "calloc".
rdma-core-29.0/infiniband-diags/ibtracert.c:545: var_assign: Assigning: "node" = storage returned from "calloc(1UL, 296UL)".
rdma-core-29.0/infiniband-diags/ibtracert.c:551: noescape: Resource "node" is not freed or pointed-to in "get_node".
rdma-core-29.0/infiniband-diags/ibtracert.c:553: leaked_storage: Variable "node" going out of scope leaks the storage it points to.
|#  551|   	if (get_node(node, port, from) < 0) {
|#  552|   		IBWARN("can't reach node %s", portid2str(from));
|#  553|-> 		return NULL;
|#  554|   	}
|#  555|

Error: RESOURCE_LEAK (CWE-772):
rdma-core-29.0/infiniband-diags/ibtracert.c:548: alloc_fn: Storage is returned from allocation function "calloc".
rdma-core-29.0/infiniband-diags/ibtracert.c:548: var_assign: Assigning: "port" = storage returned from "calloc(1UL, 112UL)".
rdma-core-29.0/infiniband-diags/ibtracert.c:551: noescape: Resource "port" is not freed or pointed-to in "get_node".
rdma-core-29.0/infiniband-diags/ibtracert.c:553: leaked_storage: Variable "port" going out of scope leaks the storage it points to.
|#  551|   	if (get_node(node, port, from) < 0) {
|#  552|   		IBWARN("can't reach node %s", portid2str(from));
|#  553|-> 		return NULL;
|#  554|   	}
|#  555|

Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>