tests: Pass the specified gid index to u.get_global_route()
test_create_ah() or test_destroy_ah() always triggered the following
error on SoftRoCE because the specified gid index didn't work.

$ bin/run_tests.py --dev rxe_enp0s5 --gid 1 -v tests.test_addr.AHTest.test_create_ah
test_create_ah (tests.test_addr.AHTest)
Test ibv_create_ah. ... ERROR

======================================================================
ERROR: test_create_ah (tests.test_addr.AHTest)
Test ibv_create_ah.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/rdma-core/tests/test_addr.py", line 51, in test_create_ah
    raise ex
  File "/root/rdma-core/tests/test_addr.py", line 47, in test_create_ah
    AH(pd, attr=ah_attr)
  File "addr.pyx", line 410, in pyverbs.addr.AH.__init__
pyverbs.pyverbs_error.PyverbsRDMAError: Failed to create AH. Errno: 110, Connection timed out

----------------------------------------------------------------------
Ran 1 test in 1.271s

FAILED (errors=1)

Try to fix the issue by passing the specified gid index to u.get_global_route().

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>