kernel-boot: correct precision specifier
[ Upstream commit c2ae19d1c5118e2eee36647956e26cab7a8029be ]

Error: DC.STREAM_BUFFER (CWE-120): [#def50]
rdma-core-28.0/kernel-boot/rdma_rename.c:171: dont_call: "fscanf" assumes an arbitrarily long string, so callers must use correct precision specifiers or never use "fscanf".
rdma-core-28.0/kernel-boot/rdma_rename.c:171: remediation: Use correct precision specifiers or implement your own parsing.
|#  169|   		}
|#  170|
|#  171|-> 		ret = fscanf(fp, "%s", address);
|#  172|   		fclose(fp);
|#  173|

Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>