tests: Fix exception when no IB device found
[ Upstream commit 02036417187f311ce04b300fceccf1de98ad50a3 ]

Avoid the following exception when no IB device found by modifying the
ParentDomainTestCase to inherit from RDMATestCase that skip the
test if there is no IB device.

ERROR: test_default_allocators (tests.test_parent_domain.ParentDomainTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kheib/git/upstream/rdma-core/tests/test_parent_domain.py", line 35, in setUp
    dev = d.get_device_list()[-1]
IndexError: list index out of range

Fixes: 4fec673 ("tests: Add a test for parent domain")
Signed-off-by: Kamal Heib <kamalheib1@gmail.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>