qedr: Fix USE_AFTER_FREE issues
[ Upstream commit 8f3ce6f9e999104cc070ba4674a147aed0251a1b ]

Error: USE_AFTER_FREE (CWE-416): [#def59]
rdma-core-28.0/providers/qedr/qelr_verbs.c:194: freed_arg: "free" frees "vmr".
rdma-core-28.0/providers/qedr/qelr_verbs.c:196: pass_freed_arg: Passing freed pointer "vmr" as an argument to "fprintf".
|#  194|   	free(vmr);
|#  195|
|#  196|-> 	DP_VERBOSE(cxt->dbg_fp, QELR_MSG_MR,
|#  197|   		   "MR DERegister %p completed successfully\n", vmr);
|#  198|   	return 0;

Error: USE_AFTER_FREE (CWE-416): [#def60]
rdma-core-28.0/providers/qedr/qelr_verbs.c:324: freed_arg: "free" frees "cq".
rdma-core-28.0/providers/qedr/qelr_verbs.c:326: pass_freed_arg: Passing freed pointer "cq" as an argument to "fprintf".
|#  324|   	free(cq);
|#  325|
|#  326|-> 	DP_VERBOSE(cxt->dbg_fp, QELR_MSG_CQ,
|#  327|   		   "destroy cq: successfully destroyed %p\n", cq);
|#  328|

Error: USE_AFTER_FREE (CWE-416): [#def61]
rdma-core-28.0/providers/qedr/qelr_verbs.c:1059: freed_arg: "free" frees "qp".
rdma-core-28.0/providers/qedr/qelr_verbs.c:1061: pass_freed_arg: Passing freed pointer "qp" as an argument to "fprintf".
|# 1059|   	free(qp);
|# 1060|
|# 1061|-> 	DP_VERBOSE(cxt->dbg_fp, QELR_MSG_QP,
|# 1062|   		   "destroy cq: successfully destroyed %p\n", qp);
|# 1063|

Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>