Fix shiftTooManyBitsSigned issues
[ Upstream commit 4a0245ed5fe84070b48d2212083732403a59662a ]

Error: CPPCHECK_WARNING:
rdma-core-28.0/infiniband-diags/ibportstate.c:245: error[shiftTooManyBitsSigned]: Shifting signed 32-bit value by 31 bits is undefined behaviour
|#  243|     mod = portnum;
|#  244|     if (espeed_cap)
|#  245|->       mod |= 1<<31;
|#  246|     if (!smp_set_via(data, dest, IB_ATTR_PORT_INFO, mod, 0, srcport))
|#  247|         IBEXIT("smp set portinfo failed");

Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>