cbuild: Fix packaging of SuSE leap
[ Upstream commit c0c0bd3d2425f5ba207dc07d859578867642fd7c ]

[ Upstream commit b4d0f866886a1a4df07b7204125516d068aa092c ]

Build without curl-mini to satisfy SuSE leap dependency.

_  rdma-core git:(pyverbs) ./buildlib/cbuild pkg leap
error: Failed build dependencies:
        curl-mini is needed by rdma-core-22.0-0.x86_64

Signed-off-by: Leon Romanovsky <leonro@mellanox.com>
Reviewed-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>