srp: Fix redhat packaging
Build fails with:

error: Installed (but unpackaged) file(s) found:
   /usr/sbin/srp_daemon.sh
    Installed (but unpackaged) file(s) found:
   /usr/sbin/srp_daemon.sh

Since we do not install the init.d script for srp on RH, also delete
the srp_daemon.sh, which is now only used by init.d.

Fixes: 1c7fe513e3e9 ("srp_daemon: One systemd service per port")
Signed-off-by: Jason Gunthorpe <jgunthorpe@obsidianresearch.com>