buildlib: disable symbol version check
Commit 9ecf3d015675 ("mlx5: Fix mlx5dv_create_flow to keep legacy ABI")
and added a new symbol that bumped the libmlx5 version to 1.25.1

Build scripts do not support this new .1 minor number in library versioning,
and complain about the symbol version being newer than the library version:
ValueError: Symbol version 'MLX5_1.25' implied by filename 'libmlx5.so.1.25.60.1' not the newest in ELF

Disable the check on this stable branch.

Signed-off-by: Nicolas Morey <nmorey@suse.com>