iwarp_pm_helper.c: fix RESOURCE_LEAK issue
[ Upstream commit 271b0190c6bae18949e0b8d033f076b7f675de0d ]

Error: RESOURCE_LEAK (CWE-772):
rdma-core-29.0/iwpmd/iwarp_pm_helper.c:407: open_arg: "get_iwpm_tcp_port" opens handle stored into "new_sd".
rdma-core-29.0/iwpmd/iwarp_pm_helper.c:416: leaked_handle: Handle variable "new_sd" going out of scope leaks the handle.
|#  414|   	iwpm_debug(IWARP_PM_ALL_DBG, "reopen_iwpm_mapped_port: Could not make port mapping (%s).\n",
|#  415|   			str_err);
|#  416|-> 	return NULL;
|#  417|   }
|#  418|
Signed-off-by: Honggang Li <honli@redhat.com>

Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>