Fix compilation on i386 with gcc
[ Upstream commit ae1b100cbcf04da16baf1197255099d5c98e1627 ]

Fix few compilation issues in i386 with the below pattern of errors.

../providers/hns/hns_roce_u_hw_v2.c: In function 'set_atomic_seg':
../providers/hns/hns_roce_u_hw_v2.c:93:12: error: cast to pointer from
integer of different size [-Werror=int-to-pointer-cast]
            (void *)wr->wr.atomic.swap);

../providers/mlx5/dr_dbg.c:91:29: error: cast from pointer to integer of
different size [-Werror=pointer-to-int-cast]

Fixes: 75d4465d962b ("mlx5: Add support for dr_rule to the steering dump API")
Fixes: b8c02c0039c4 ("libhns: Add support for extended atomic")
Signed-off-by: Yishai Hadas <yishaih@mellanox.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>