verbs: fix compilation error with ICC
Compiling a program including verbs.h with ICC fails with the following
error (seen with DPDK):

 /root/development/rdma-core/build/include/infiniband/verbs.h(84):
 warning #61: integer operation result is out of range
   static void *__VERBS_ABI_IS_EXTENDED = ((uint8_t *) NULL) - 1;

Fixes: 6be16586e081 ("Infrastructure to support verbs extensions")
Cc: yishaih@mellanox.com

Signed-off-by: Nelio Laranjeiro <nelio.laranjeiro@6wind.com>
Acked-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>
Signed-off-by: Leon Romanovsky <leon@kernel.org>