irdma: Remove unused _total_size
Fixes clang 15 warning:

providers/irdma/uk.c:956:8: error: variable 'total_size' set but not used [-Werror,-Wunused-but-set-variable]
        __u32 total_size = 0, wqe_idx, i, byte_off;

Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>