tests: Set port_space based on link_layer
To avoid the following failure when running test_rdmacm over ib_qib,
make sure to set the port_space to RDMA_PS_IPOIB when the port is set to
INFINIBAND.

======================================================================
ERROR: test_rdmacm_async_ex_multicast_traffic (tests.test_rdmacm.CMTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rdma-core/tests/utils.py", line 912, in inner
    return func(instance)
  File "/home/rdma-core/tests/test_rdmacm.py", line 181, in test_rdmacm_async_ex_multicast_traffic
    self.two_nodes_rdmacm_traffic(CMAsyncConnection,
  File "/home/rdma-core/tests/test_rdmacm.py", line 88, in two_nodes_rdmacm_traffic
    raise(res)
threading.BrokenBarrierError

Signed-off-by: Kamal Heib <kamalheib1@gmail.com>