verbs: Pass the cmd to execute_cmd through a void *
gcc complains about:

In function '_execute_cmd_write',
    inlined from 'ibv_create_comp_channel' at ../libibverbs/verbs.c:509:6:
../libibverbs/cmd_fallback.c:250:13: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
           if (write(ctx->cmd_fd, req, req_size) != req_size)

Which is because 'req' is extending past hdr which was used to pass
in the struct. This code is effectively doing something like container_of().

Pass the entire struct through as a void * to avoid the warning.

Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>