verbs: Simplify the logic assigning vid in ibv_resolve_eth_l2_from_gid()
gcc 10 with LTO reports:

../libibverbs/verbs.c:1040:8: error: 'ret_vid' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 1040 |   *vid = ret_vid;

Which seems like a compiler bug as there is obviously no way for this to
be true, nor is it clear how LTO has any impact here since
neigh_get_vlan_id_from_dev() always returns a defined value.

Nevertheless, the logic is tortured, so simplify it by combining
everything into one if.

Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>