rxe: fix rxe compilation with newer kernels
Newer kernels have heder that conflicts with rxe.h:
In file included from ../providers/rxe/rxe.h:42:0,
                 from ../providers/rxe/rxe.c:57:
/usr/include/rdma/rdma_user_rxe.h:156:8: error: redefinition of 'struct rxe_create_cq_resp'
 struct rxe_create_cq_resp {
        ^~~~~~~~~~~~~~~~~~
In file included from ../providers/rxe/rxe.c:56:0:
../providers/rxe/rxe-abi.h:51:8: note: originally defined here
 struct rxe_create_cq_resp {
        ^~~~~~~~~~~~~~~~~~
In file included from ../providers/rxe/rxe.h:42:0,
                 from ../providers/rxe/rxe.c:57:
/usr/include/rdma/rdma_user_rxe.h:160:8: error: redefinition of 'struct rxe_resize_cq_resp'

Detect rxe compilation failures and in those cases,
 shadow the kernel header with the one in buildlib/fix-include

Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>