ocrdma: Remove unused discard_cnt
Fixes clang 15 warning:

providers/ocrdma/ocrdma_verbs.c:984:6: error: variable 'discard_cnt' set but not used [-Werror,-Wunused-but-set-variable]
        int discard_cnt = 0;

Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>