tests: Require being root to run test_obj_on_huge
[ Upstream commit 0c640f48499c706269fa4d5a137dcc5dcf9f180b ]

[leonro@vm ~]$  ~/build/bin/run_tests.py -v -k test_obj_on_huge
test_obj_on_huge (tests.test_mlx5_huge_page.ResourcesOnHugePageTest.test_obj_on_huge)
Test HUGE allocation type for srq cq and qp. ... ERROR

======================================================================
ERROR: test_obj_on_huge (tests.test_mlx5_huge_page.ResourcesOnHugePageTest.test_obj_on_huge)
Test HUGE allocation type for srq cq and qp.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/rdma-core/tests/test_mlx5_huge_page.py", line 60, in test_obj_on_huge
    self.create_objects()
  File "/rdma-core/tests/test_mlx5_huge_page.py", line 41, in create_objects
    self.create_cq()
  File "/rdma-core/tests/test_mlx5_huge_page.py", line 22, in create_cq
    return CQ(self.ctx, 100, None, None, 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cq.pyx", line 102, in pyverbs.cq.CQ.__init__
pyverbs.pyverbs_error.PyverbsRDMAError: Failed to create a CQ. Errno: 0, Success

----------------------------------------------------------------------
Ran 1 test in 0.036s

FAILED (errors=1)

Fixes: 8d0364ffa42d ("tests: Add huge page allocation tests")
Signed-off-by: Leon Romanovsky <leonro@nvidia.com>
Signed-off-by: Nicolas Morey <nmorey@suse.com>