vmw_pvrdma: Fix uninit_use issue
[ Upstream commit a25f6f15a92bfc2b82f82bfcd04d488227e79ee6 ]

Fix the following issues:
Error: UNINIT (CWE-457): [#def152] [important]
providers/vmw_pvrdma/pvrdma_main.c:115:2: var_decl: Declaring variable "resp" without initializer.
providers/vmw_pvrdma/pvrdma_main.c:122:2: uninit_use: Using uninitialized value "resp.qp_tab_size".

Error: UNINIT (CWE-457): [#def153] [important]
providers/vmw_pvrdma/qp.c:111:2: var_decl: Declaring variable "resp" without initializer.
providers/vmw_pvrdma/qp.c:150:2: uninit_use: Using uninitialized value "resp.srqn".

Fixes: 4c8ed14eb6b7 ("vmw_pvrdma: Add SRQ support")
Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Nicolas Morey <nmorey@suse.com>