mlx5: Fix compilation on 32 bit systems when sse3 is on
[ Upstream commit 708c82428aed6141c1b235524f39dfdef6a4b0cd ]

On 32 bit systems when sse3 is on below error is set as of the '>> 32'
on a 32 width of type.

Fix by converting into uint64_t before doing the shifting.

error: right shift count >= width of type [-Werror]
__m128i val  = _mm_set_epi32((uint32_t)address, (uint32_t)(address >> 32),
                             lkey, length);

Fixes: 00c91653ef9a ("mlx5: Add WQE segments implementation")
Cc: stable@linux-rdma.org
Signed-off-by: Yishai Hadas <yishaih@mellanox.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>