tests: Make sure to set dlid when creating AH
To avoid the following failure when running test_addr over ib_qib,
make sure to set the dlid when the port is set to INFINIBAND.

======================================================================
ERROR: test_create_ah (tests.test_addr.AHTest)
Test ibv_create_ah.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rdma-core/tests/test_addr.py", line 49, in test_create_ah
    raise ex
  File "/home/rdma-core/tests/test_addr.py", line 45, in test_create_ah
    AH(pd, attr=ah_attr)
  File "addr.pyx", line 410, in pyverbs.addr.AH.__init__
pyverbs.pyverbs_error.PyverbsRDMAError: Failed to create AH. Errno: 22, Invalid argument

Signed-off-by: Kamal Heib <kamalheib1@gmail.com>