tests: poll_cq: Don't pass wc.status to PyverbsRDMAError
When testing fails, below we got below confusing error message due to the
wrong errno:
    u.rdma_traffic(client, server, self.iters, self.gid_index, self.ib_port,
  File "rdma-core/tests/utils.py", line 1013, in rdma_traffic
    poll_cq(client.cq)
  File "rdma-core/tests/utils.py", line 577, in poll_cq
    raise PyverbsRDMAError('Completion status is {s}'.
pyverbs.pyverbs_error.PyverbsRDMAError: Completion status is local QP operation error. Errno: 2, No such file or directory

That's because PyverbsRDMAError(msg, errno) accept the 2nd parameter as
errno.

Signed-off-by: Li Zhijian <lizhijian@fujitsu.com>