srp_daemon: check return value of function 'umad_init'
[ Upstream commit 00dba86f407cf858ee801cf572c8bc76903e31c2 ]

Error: CHECKED_RETURN (CWE-252):
rdma-core-28.0/srp_daemon/srp_daemon.c:2164: check_return: Calling "umad_init" without checking return value (as is done elsewhere 8 out of 10 times).
rdma-core-28.0/ibacm/src/acm.c:3331: example_checked: Example 1: "umad_init()" has its value checked in "umad_init() != 0".
rdma-core-28.0/infiniband-diags/ibstat.c:305: example_checked: Example 2: "umad_init()" has its value checked in "umad_init() < 0".
rdma-core-28.0/infiniband-diags/saquery.c:1855: example_checked: Example 3: "umad_init()" has its value checked in "umad_init()".
rdma-core-28.0/infiniband-diags/smpdump.c:217: example_checked: Example 4: "umad_init()" has its value checked in "umad_init() < 0".
rdma-core-28.0/libibmad/rpc.c:385: example_checked: Example 5: "umad_init()" has its value checked in "umad_init() < 0".
|# 2162|     }
|# 2163|
|# 2164|->   umad_init();
|# 2165|     res = alloc_res();
|# 2166|     if (!res) {

Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>