tests: Add a timeout mechanism
Some tests, especially those involving traffic, might hang sometimes
due to dropped packets, bugs etc. During execution of run_tests.py,
such issues stuck the run indefinitely.
Python's unittest framework does not provide a builtin timeout
mechanism, but the signal module can be used to achieve such behavior.

Register a handler for SIGALRM that simply raises a PyverbsError if
it expires (the rest of the tests will continue to run as usual).
Provide a decorator to wrap a test method call with a setting of a
timer (3 seconds, as this is more than enough time for our tests).
Decorate traffic methods with the above decorator.

An execution with an expired timeout will look as follows:

$ python3 /usr/share/doc/rdma-core-28.0/tests/run_tests.py --verbose -k
test_cqex
test_rc_traffic_cq_ex (tests.test_cqex.CqExTestCase) ... ok
test_ud_traffic_cq_ex (tests.test_cqex.CqExTestCase) ... ERROR
test_xrc_traffic_cq_ex (tests.test_cqex.CqExTestCase) ... ok

======================================================================
ERROR: test_ud_traffic_cq_ex (tests.test_cqex.CqExTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/doc/rdma-core-28.0/tests/utils.py", line 46, in func_wrapper
    func(func_self)
  File "/usr/share/doc/rdma-core-28.0/tests/test_cqex.py", line 69, in test_ud_traffic_cq_ex
    is_cq_ex=True)
  File "/usr/share/doc/rdma-core-28.0/tests/utils.py", line 439, in traffic
    poll(server.cq)
  File "/usr/share/doc/rdma-core-28.0/tests/utils.py", line 373, in poll_cq_ex
    ret = cqex.start_poll(poll_attr)
  File "/usr/share/doc/rdma-core-28.0/tests/utils.py", line 37, in sig_handler
    raise PyverbsError('Timeout expired')
pyverbs.pyverbs_error.PyverbsError: Timeout expired

----------------------------------------------------------------------
Ran 3 tests in 3.149s

FAILED (errors=1)

Signed-off-by: Noa Osherovich <noaos@mellanox.com>
Reviewed-by: Edward Srouji <edwards@mellanox.com>