infiniband-diags: Fix two Coverity 'invalidScanfFormatWidth' issues
[ Upstream commit 5c80749b00e7aae64f8c99d03657ad296efcd777 ]

Error: CPPCHECK_WARNING (CWE-120): [#def33]
rdma-core-28.0/infiniband-diags/ibtracert.c:935: error[invalidScanfFormatWidth]: Width 20 given in format string (no. 1) is larger than destination buffer 'srcbuf[20]', use %19s to prevent overflowing it.
|#  933|   				continue;	/* ignore comment lines */
|#  934|
|#  935|-> 			if (sscanf(portsbuf, "%20s %20s", srcbuf, dstbuf) != 2)
|#  936|   				IBEXIT("ports-file, %s, at line %i contains bad data",
|#  937|   					ports_file, line_count);

Error: CPPCHECK_WARNING (CWE-120): [#def34]
rdma-core-28.0/infiniband-diags/ibtracert.c:935: error[invalidScanfFormatWidth]: Width 20 given in format string (no. 2) is larger than destination buffer 'dstbuf[20]', use %19s to prevent overflowing it.
|#  933|   				continue;	/* ignore comment lines */
|#  934|
|#  935|-> 			if (sscanf(portsbuf, "%20s %20s", srcbuf, dstbuf) != 2)
|#  936|   				IBEXIT("ports-file, %s, at line %i contains bad data",
|#  937|   					ports_file, line_count);

Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>