infiniband-diags: Fix memory leaks in ibroute.c
[ Upstream commit 5072f2203231c43f445b910fdbe4c4c0ebc479f4 ]

Error: RESOURCE_LEAK (CWE-772): [#def40]
rdma-core-28.0/infiniband-diags/ibroute.c:176: alloc_fn: Storage is returned from allocation function "remap_node_name".
rdma-core-28.0/infiniband-diags/ibroute.c:176: var_assign: Assigning: "mapnd" = storage returned from "remap_node_name(node_name_map, nodeguid, nd)".
rdma-core-28.0/infiniband-diags/ibroute.c:178: noescape: Resource "mapnd" is not freed or pointed-to in "printf".
rdma-core-28.0/infiniband-diags/ibroute.c:220: leaked_storage: Variable "mapnd" going out of scope leaks the storage it points to.
|#  218|   						"; MAD status 0x%x AM 0x%x\n",
|#  219|   						status, mod);
|#  220|-> 				return NULL;
|#  221|   			}
|#  222|   		}

Error: RESOURCE_LEAK (CWE-772): [#def41]
rdma-core-28.0/infiniband-diags/ibroute.c:348: alloc_fn: Storage is returned from allocation function "remap_node_name".
rdma-core-28.0/infiniband-diags/ibroute.c:348: var_assign: Assigning: "mapnd" = storage returned from "remap_node_name(node_name_map, nodeguid, nd)".
rdma-core-28.0/infiniband-diags/ibroute.c:350: noescape: Resource "mapnd" is not freed or pointed-to in "printf".
rdma-core-28.0/infiniband-diags/ibroute.c:368: leaked_storage: Variable "mapnd" going out of scope leaks the storage it points to.
|#  366|   					"; MAD status 0x%x AM 0x%x\n",
|#  367|   					status, block);
|#  368|-> 			return NULL;
|#  369|   		}
|#  370|   		i = block * IB_SMP_DATA_SIZE;
Signed-off-by: Honggang Li <honli@redhat.com>

Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>