libibumad: Check for error returns in get_port()
Stronger control flow analysis on GCC 10 with LTO detects:

../libibumad/umad.c: In function 'get_port':
../libibumad/umad.c:208:20: error: 'val' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  208 |   port->pkeys[idx] = val;

Caused by ignoring the return code from sys_read_uint()

Reorganize the goto unwind so it makes sense and check all the calls to
sys_read_uint().

Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>