xsrq_pingpong.c: Fix RESOURCE_LEAK issue
[ Upstream commit 671b3e12a0694419ba6a6511c154dea07e1d7a71 ]

Error: RESOURCE_LEAK (CWE-772):
rdma-core-29.0/libibverbs/examples/xsrq_pingpong.c:581: open_fn: Returning handle opened by "socket". [Note: The source code implementation of the function has been overridden by a builtin model.]
rdma-core-29.0/libibverbs/examples/xsrq_pingpong.c:581: var_assign: Assigning: "sockfd" = handle returned from "socket(t->ai_family, t->ai_socktype, t->ai_protocol)".
rdma-core-29.0/libibverbs/examples/xsrq_pingpong.c:583: noescape: Resource "sockfd" is not freed or pointed-to in "connect". [Note: The source code implementation of the function has been overridden by a builtin model.]
rdma-core-29.0/libibverbs/examples/xsrq_pingpong.c:598: noescape: Resource "sockfd" is not freed or pointed-to in "send_local_dest".
rdma-core-29.0/libibverbs/examples/xsrq_pingpong.c:599: leaked_handle: Handle variable "sockfd" going out of scope leaks the handle.
|#  597|
|#  598|   	if (send_local_dest(sockfd, 0))
|#  599|-> 		return 1;
|#  600|
|#  601|   	if (recv_remote_dest(sockfd, 0))

Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>