qedr: fix USE_AFTER_FREE issue
Issue was detected by Coverity.

Error: USE_AFTER_FREE (CWE-416): [#def10]
rdma-core-33.0/providers/qedr/qelr_verbs.c:2678: freed_arg: "free" frees "srq".
rdma-core-33.0/providers/qedr/qelr_verbs.c:2680: pass_freed_arg: Passing freed pointer "srq" as an argument to "fprintf".
|# 2678|   	free(srq);
|# 2679|   err0:
|# 2680|-> 	DP_ERR(cxt->dbg_fp,
|# 2681|   	       "create srq: failed to create %p. rc=%d\n", srq, rc);
|# 2682|   	return NULL;

Fixes: cae4a99ae679 ("libqedr: add support for XRC-SRQ's.")
Signed-off-by: Honggang Li <honli@redhat.com>