mlx4: Fix uninit_use issues
[ Upstream commit 3ca882f24370234ac4b60b0400d201b37a253f77 ]

Fix the following uninit_use issues:
Error: UNINIT (CWE-457): [#def111] [important]
providers/mlx4/mlx4.c:146:2: var_decl: Declaring variable "resp_v3" without initializer.
providers/mlx4/mlx4.c:163:3: uninit_use: Using uninitialized value "resp_v3.qp_tab_size".

Error: UNINIT (CWE-457): [#def112] [important]
providers/mlx4/mlx4.c:144:2: var_decl: Declaring variable "resp" without initializer.
providers/mlx4/mlx4.c:171:3: uninit_use: Using uninitialized value "resp.qp_tab_size".

Error: UNINIT (CWE-457): [#def113] [important]
providers/mlx4/verbs.c:53:2: var_decl: Declaring variable "resp" without initializer.
providers/mlx4/verbs.c:67:3: uninit_use: Using uninitialized value "resp.rss_caps.rx_hash_fields_mask".

Error: UNINIT (CWE-457): [#def114] [important]
providers/mlx4/verbs.c:53:2: var_decl: Declaring variable "resp" without initializer.
providers/mlx4/verbs.c:73:3: uninit_use: Using uninitialized value "resp.tso_caps.max_tso".

Error: UNINIT (CWE-457): [#def115] [important]
providers/mlx4/verbs.c:456:2: var_decl: Declaring variable "resp" without initializer.
providers/mlx4/verbs.c:469:3: uninit_use: Using uninitialized value "resp.cqn".

Fixes: 90b1f7f28ef2 ("providers: Remove normal query_device() from providers that have _ex")
Fixes: 9a9017688062 ("Add support for 64B CQEs")
Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Nicolas Morey <nmorey@suse.com>