pyverbs: Fix PyverbsRDMAErrno() takes exactly one argument (2 given)
Avoid the following failure by call PyverbsRDMAErrno() with the exact number
of arguments.

Traceback (most recent call last):
  File "/home/rdma-core/tests/test_odp.py", line 56, in test_odp_xrc_traffic
    client, server = self.create_players('xrc')
  File "/home/rdma-core/tests/test_odp.py", line 35, in create_players
    client = self.qp_dict[qp_type](self.dev_name, self.ib_port,
  File "/home/rdma-core/tests/base.py", line 367, in __init__
    super(XRCResources, self).__init__(dev_name, ib_port, gid_index)
  File "/home/rdma-core/tests/base.py", line 238, in __init__
    self.init_resources()
  File "/home/rdma-core/tests/base.py", line 454, in init_resources
    self.create_xrcd()
  File "/home/rdma-core/tests/base.py", line 413, in create_xrcd
    self.xrcd = XRCD(self.ctx, init)
  File "xrcd.pyx", line 54, in pyverbs.xrcd.XRCD.__init__
TypeError: PyverbsRDMAErrno() takes exactly one argument (2 given)

Fixes: b68ce6f476cb ("pyverbs: Introducing XRCD class")
Signed-off-by: Kamal Heib <kamalheib1@gmail.com>