ibstatus - small script change
The ibstatus script, in infiniband-diags, doesn't tolerate a missing
device very well. This small fix makes the output a bit more useful.

Before: $ ibstatus
/usr/bin/ibstatus: line 60: cd: /sys/class/infiniband: No such file or directory
Fatal error:  device '8cpu-mdout.8hoursamber8-8hr-2007-09-06-01:52:23': sys
files not found
(/sys/class/infiniband/8cpu-mdout.8hoursamber8-8hr-2007-09-06-01:52:23/ports)

After: $ ibstatus
Fatal error:  No devices

Thanks for considering this!

Jeremy

Signed-off-by: Sasha Khapyorsky <sashak@voltaire.com>