infiniband-diags: Fix memory leak in read_ibdiag_config
[ Upstream commit d034e23b757237b0016188ac42934492aa8e8bb2 ]

Error: RESOURCE_LEAK (CWE-772): [#def38]
rdma-core-28.0/infiniband-diags/ibdiag_common.c:167: alloc_fn: Storage is returned from allocation function "strdup".
rdma-core-28.0/infiniband-diags/ibdiag_common.c:167: var_assign: Assigning: "ibd_nd_format" = storage returned from "strdup(val_str)".
rdma-core-28.0/infiniband-diags/ibdiag_common.c:167: overwrite_var: Overwriting "ibd_nd_format" in "ibd_nd_format = strdup(val_str)" leaks the storage that "ibd_nd_format" points to.
|#  165|   		} else if (strncmp(name, "nd_format",
|#  166|   				   strlen("nd_format")) == 0) {
|#  167|-> 			ibd_nd_format = strdup(val_str);
|#  168|   		}
|#  169|   	}

Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>