cxgb4: Fix uninit_use issues
[ Upstream commit 67bd87ae81d2c2d0459e36e5936ee0b421462b73 ]

Error: UNINIT (CWE-457): [#def102] [important]
providers/cxgb4/verbs.c:280:2: var_decl: Declaring variable "resp" without initializer.
providers/cxgb4/verbs.c:303:2: uninit_use: Using uninitialized value "resp.srqid".

Error: UNINIT (CWE-457): [#def103] [important]
providers/cxgb4/verbs.c:420:2: var_decl: Declaring variable "resp" without initializer.
providers/cxgb4/verbs.c:443:2: uninit_use: Using uninitialized value "resp.qid_mask".

Error: UNINIT (CWE-457): [#def104] [important]
providers/cxgb4/verbs.c:523:2: var_decl: Declaring variable "resp" without initializer.
providers/cxgb4/verbs.c:547:2: uninit_use: Using uninitialized value "resp.qid_mask".

Fixes: d6e6ae69be5e ("Add libcxgb4 files.")
Fixes: 27a8a29f2089 ("cxgb4: Add support for user mode SRQs")
Fixes: b051a2ea9dc7 ("Support ABI 0 and 1 versions of the iwarp driver.")
Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Nicolas Morey <nmorey@suse.com>