infiniband-diags: Fix memory leak in function rereg_and_test_port
[ Upstream commit bb6436903e31efeb5578ab6ac0114282f1c65888 ]

Error: RESOURCE_LEAK (CWE-772): [#def48]
rdma-core-28.0/infiniband-diags/mcm_rereg_test.c:322: alloc_fn: Storage is returned from allocation function "calloc".
rdma-core-28.0/infiniband-diags/mcm_rereg_test.c:322: var_assign: Assigning: "list" = storage returned from "calloc(50UL, 32UL)".
rdma-core-28.0/infiniband-diags/mcm_rereg_test.c:332: leaked_storage: Variable "list" going out of scope leaks the storage it points to.
|#  330|   	if (!f) {
|#  331|   		err("cannot open %s: %s\n", guid_file, strerror(errno));
|#  332|-> 		return -1;
|#  333|   	}
|#  334|

Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>