pyverbs: Fix compilation error in Fedora 39
[ Upstream commit 0fa21ec991180b7bdd93562d02266cffad91b24e ]

Error compiling Cython file:
------------------------------------------------------------
...
        """
        super().__init__()
        self.pd = pd
        self.init_attr.pd = <v.ibv_pd*>pd.pd
        if pd_context:
            self.init_attr.alloc = pd_alloc
                                   ^
------------------------------------------------------------

/home/leonro/src/rdma-core/pyverbs/pd.pyx:230:35: Cannot assign type 'void *(ibv_pd *, void *, size_t,
size_t, uint64_t) except? NULL' to 'void *(*)(ibv_pd *, void *, size_t, size_t, uint64_t) noexcept'.
Exception values are incompatible. Suggest adding 'noexcept' to type 'void *(ibv_pd *, void *, size_t,
size_t, uint64_t) except? NULL'.

Error compiling Cython file:
------------------------------------------------------------
...
        super().__init__()
        self.pd = pd
        self.init_attr.pd = <v.ibv_pd*>pd.pd
        if pd_context:
            self.init_attr.alloc = pd_alloc
            self.init_attr.free = pd_free
                                  ^
------------------------------------------------------------

Signed-off-by: Leon Romanovsky <leonro@nvidia.com>
Signed-off-by: Edward Srouji <edwards@nvidia.com>
Signed-off-by: Nicolas Morey <nmorey@suse.com>