infiniband-diags: Reorder library build order
[ Upstream commit 06157c520470debd11b1c0621403295520d1acc0 ]

Attempt to raise the minimal cmake version causes to the following error:

[284/425] Linking C executable bin/ibsendtrap
FAILED: : && /usr/bin/cc  -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wformat=2 -Wformat-nonliteral -Wdate-time -Wnested-externs -Wshadow -Wstrict-prototypes -Wold-style-definition -Wredundant-decls -O2 -g  -Wl,--as-needed -Wl,--no-undefined infiniband-diags/CMakeFiles/ibsendtrap.dir/ibsendtrap.c.o  -o bin/ibsendtrap  ccan/libccan.a util/librdma_util.a lib/libibumad.so.3.2.35.0 lib/libibmad.so.5.3.35.0 infiniband-diags/libibdiags_tools.a -Wl,-rpath,/home/leonro/src/rdma-core/build-ubuntu-16.04/lib && :
/usr/bin/ld: infiniband-diags/libibdiags_tools.a(ibdiag_common.c.o): undefined reference to symbol 'umad_release_port@@IBUMAD_1.0'
lib/libibumad.so.3.2.35.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[284/425] Building C object providers/mlx5/CMakeFiles/mlx5.dir/cq.c.o
ninja: build stopped: subcommand failed.

This is happening because infiniband-diags links common files in wrong order.

Fixes: 58670e0a17ba ("ibdiags: Add cmake files for ibdiags components")
Signed-off-by: Leon Romanovsky <leonro@nvidia.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>