ibacm: fix a RESOURCE_LEAK issue for acmp.c
[ Upstream commit 498953489ded95b74aed0bd9067b8d7dee2e4991 ]

Error: RESOURCE_LEAK (CWE-772):
rdma-core-29.0/ibacm/prov/acmp/src/acmp.c:2415: alloc_fn: Storage is returned from allocation function "malloc".
rdma-core-29.0/ibacm/prov/acmp/src/acmp.c:2415: var_assign: Assigning: "addr_ctx" = storage returned from "malloc(16UL)".
rdma-core-29.0/ibacm/prov/acmp/src/acmp.c:2433: leaked_storage: Variable "addr_ctx" going out of scope leaks the storage it points to.
|# 2431|   			addr->id_string);
|# 2432|   		memset(&ep->addr_info[i], 0, sizeof(ep->addr_info[i]));
|# 2433|-> 		return -1;
|# 2434|   	}
|# 2435|

Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>