ibacm: fix a REVERSE_INULL issue
Error: REVERSE_INULL (CWE-476):
rdma-core-28.0/ibacm/prov/acmp/src/acmp.c:1769: deref_ptr: Directly dereferencing pointer "iap->ifa_addr".
rdma-core-28.0/ibacm/prov/acmp/src/acmp.c:1771: check_after_deref: Null-checking "iap->ifa_addr" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
|# 1769|     s_family = iap->ifa_addr->sa_family;
|# 1770|
|# 1771|->   if (!iap->ifa_addr ||
|# 1772|         !(iap->ifa_flags & IFF_UP) ||
|# 1773|         (s_family != d_family))

Signed-off-by: Honggang Li <honli@redhat.com>