mlx5: Fix compilation on 32 bit systems with gcc 7.5
Fix some compilation issues as of below on 32 bit systems with gcc 7.5.
error: cast from pointer to integer of different size
[-Werror=pointer-to-int-cast]

Fixes: aa0fda858014 ("mlx5: Introduce mlx5dv_wr_memcpy builder")
Fixes: 47ee212d2aaa ("mlx5: Support initial DEVX/DV APIs over vfio")

Signed-off-by: Yishai Hadas <yishaih@nvidia.com>