rxe: Fix uninit_use_in_call issues
[ Upstream commit ac976066469e26c0223e9f229217aecbfa0adc4a ]

Fix the following issues:
Error: UNINIT (CWE-457): [#def142] [important]
providers/rxe/rxe.c:584:2: var_decl: Declaring variable "resp" without initializer.
providers/rxe/rxe.c:600:2: uninit_use_in_call: Using uninitialized value "resp.mi.size" when calling "mmap".

Error: UNINIT (CWE-457): [#def143] [important]
rdma-core-54.0/providers/rxe/rxe.c:623:2: var_decl: Declaring variable "resp" without initializer.
rdma-core-54.0/providers/rxe/rxe.c:639:2: uninit_use_in_call: Using uninitialized value "resp.mi.size" when calling "mmap".

Fixes: e05647a484a5 ("providers/rxe: Implement create_srq_ex")
Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Nicolas Morey <nmorey@suse.com>