Revert "vmw_pvrdma: Add SRQ support" because it causes build failures
-- Missing Optional Items:
--  Valgrind memcheck.h NOT enabled
--  Valgrind drd.h NOT enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/leonro/src/rdma-core/build
[1/81] Linking C shared module lib/libhfi1verbs-rdmav16.so
[2/81] Building C object providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/pvrdma_main.c.o
FAILED: providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/pvrdma_main.c.o
/usr/lib/ccache/bin/cc -Dvmw_pvrdma_rdmav16_EXPORTS -Iinclude -I/usr/include/libnl3 -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wformat=2 -Wshadow -Wstrict-prototypes -Wold-style-definition -Wredundant-decls -O2 -g  -fPIC   -std=gnu11 -MD -MT providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/pvrdma_main.c.o -MF providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/pvrdma_main.c.o.d -o providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/pvrdma_main.c.o   -c ../providers/vmw_pvrdma/pvrdma_main.c
In file included from ../providers/vmw_pvrdma/pvrdma_main.c:46:0:
../providers/vmw_pvrdma/pvrdma.h: In function ‘pvrdma_write_uar_srq’:
../providers/vmw_pvrdma/pvrdma.h:244:20: error: ‘PVRDMA_UAR_SRQ_OFFSET’ undeclared (first use in this function); did you mean ‘PVRDMA_UAR_CQ_OFFSET’?
  *(__le32 *)(uar + PVRDMA_UAR_SRQ_OFFSET) = htole32(value);
                    ^~~~~~~~~~~~~~~~~~~~~
                    PVRDMA_UAR_CQ_OFFSET
../providers/vmw_pvrdma/pvrdma.h:244:20: note: each undeclared identifier is reported only once for each function it appears in
[3/81] Building C object providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/qp.c.o
FAILED: providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/qp.c.o
/usr/lib/ccache/bin/cc -Dvmw_pvrdma_rdmav16_EXPORTS -Iinclude -I/usr/include/libnl3 -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wformat=2 -Wshadow -Wstrict-prototypes -Wold-style-definition -Wredundant-decls -O2 -g  -fPIC   -std=gnu11 -MD -MT providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/qp.c.o -MF providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/qp.c.o.d -o providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/qp.c.o   -c ../providers/vmw_pvrdma/qp.c
In file included from ../providers/vmw_pvrdma/qp.c:48:0:
../providers/vmw_pvrdma/pvrdma.h: In function ‘pvrdma_write_uar_srq’:
../providers/vmw_pvrdma/pvrdma.h:244:20: error: ‘PVRDMA_UAR_SRQ_OFFSET’ undeclared (first use in this function); did you mean ‘PVRDMA_UAR_CQ_OFFSET’?
  *(__le32 *)(uar + PVRDMA_UAR_SRQ_OFFSET) = htole32(value);
                    ^~~~~~~~~~~~~~~~~~~~~
                    PVRDMA_UAR_CQ_OFFSET
../providers/vmw_pvrdma/pvrdma.h:244:20: note: each undeclared identifier is reported only once for each function it appears in
../providers/vmw_pvrdma/qp.c: In function ‘pvrdma_create_srq’:
../providers/vmw_pvrdma/qp.c:141:12: error: ‘struct pvrdma_create_srq’ has no member named ‘buf_size’; did you mean ‘buf_addr’?
  cmd.udata.buf_size = srq->buf.length;
            ^~~~~~~~
            buf_addr
../providers/vmw_pvrdma/qp.c: In function ‘pvrdma_post_srq_recv’:
../providers/vmw_pvrdma/qp.c:704:10: error: ‘PVRDMA_UAR_SRQ_RECV’ undeclared (first use in this function); did you mean ‘PVRDMA_UAR_QP_RECV’?
          PVRDMA_UAR_SRQ_RECV | srq->srqn);
          ^~~~~~~~~~~~~~~~~~~
          PVRDMA_UAR_QP_RECV
[4/81] Building C object providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/verbs.c.o
FAILED: providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/verbs.c.o
/usr/lib/ccache/bin/cc -Dvmw_pvrdma_rdmav16_EXPORTS -Iinclude -I/usr/include/libnl3 -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wformat=2 -Wshadow -Wstrict-prototypes -Wold-style-definition -Wredundant-decls -O2 -g  -fPIC   -std=gnu11 -MD -MT providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/verbs.c.o -MF providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/verbs.c.o.d -o providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/verbs.c.o   -c ../providers/vmw_pvrdma/verbs.c
In file included from ../providers/vmw_pvrdma/verbs.c:47:0:
../providers/vmw_pvrdma/pvrdma.h: In function ‘pvrdma_write_uar_srq’:
../providers/vmw_pvrdma/pvrdma.h:244:20: error: ‘PVRDMA_UAR_SRQ_OFFSET’ undeclared (first use in this function); did you mean ‘PVRDMA_UAR_CQ_OFFSET’?
  *(__le32 *)(uar + PVRDMA_UAR_SRQ_OFFSET) = htole32(value);
                    ^~~~~~~~~~~~~~~~~~~~~
                    PVRDMA_UAR_CQ_OFFSET
../providers/vmw_pvrdma/pvrdma.h:244:20: note: each undeclared identifier is reported only once for each function it appears in
[5/81] Building C object providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/cq.c.o
FAILED: providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/cq.c.o
/usr/lib/ccache/bin/cc -Dvmw_pvrdma_rdmav16_EXPORTS -Iinclude -I/usr/include/libnl3 -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wformat=2 -Wshadow -Wstrict-prototypes -Wold-style-definition -Wredundant-decls -O2 -g  -fPIC   -std=gnu11 -MD -MT providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/cq.c.o -MF providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/cq.c.o.d -o providers/vmw_pvrdma/CMakeFiles/vmw_pvrdma-rdmav16.dir/cq.c.o   -c ../providers/vmw_pvrdma/cq.c
In file included from ../providers/vmw_pvrdma/cq.c:48:0:
../providers/vmw_pvrdma/pvrdma.h: In function ‘pvrdma_write_uar_srq’:
../providers/vmw_pvrdma/pvrdma.h:244:20: error: ‘PVRDMA_UAR_SRQ_OFFSET’ undeclared (first use in this function); did you mean ‘PVRDMA_UAR_CQ_OFFSET’?
  *(__le32 *)(uar + PVRDMA_UAR_SRQ_OFFSET) = htole32(value);
                    ^~~~~~~~~~~~~~~~~~~~~
                    PVRDMA_UAR_CQ_OFFSET
../providers/vmw_pvrdma/pvrdma.h:244:20: note: each undeclared identifier is reported only once for each function it appears in
[6/81] Building C object providers/ipathverbs/CMakeFiles/ipathverbs-rdmav16.dir/ipathverbs.c.o
[7/81] Building C object providers/ipathverbs/CMakeFiles/ipathverbs-rdmav16.dir/verbs.c.o
ninja: build stopped: subcommand failed.

This reverts commit 25f07300bfb7d2a816c8f415a1682003cd7fbf30.

Signed-off-by: Leon Romanovsky <leon@kernel.org>