libhns: Fix return value when creating unsupported QP types
[ Upstream commit fd8020e84bd82c157faa7bcd7979fae983877952 ]

Errno EVINAL has been returned when createing unsupported QP types
which caused the failure of the testcase test_query_raw_qp.

ERROR: test_query_raw_qp (tests.test_qp.QPTest)
Queries an RAW Packet QP after creation. Verifies that its properties
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test_qp.py", line 241, in test_query_raw_qp
    self.query_qp_common_test(e.IBV_QPT_RAW_PACKET)
  File "./tests/test_qp.py", line 197, in query_qp_common_test
    qp = self.create_qp(pd, qia, False, False, self.ib_port)
  File "./tests/test_qp.py", line 41, in create_qp
    raise ex
  File "./tests/test_qp.py", line 35, in create_qp
    return QP(creator, qp_init_attr, qp_attr)
  File "qp.pyx", line 982, in pyverbs.qp.QP.__init__
pyverbs.pyverbs_error.PyverbsRDMAError: Failed to create QP. Errno: 22, Invalid argument

Fixes: 13c10af17443 ("libhns: Support ibv_create_qp_ex")
Signed-off-by: Chengchang Tang <tangchengchang@huawei.com>
Signed-off-by: Haoyue Xu <xuhaoyue1@hisilicon.com>
Signed-off-by: Leon Romanovsky <leonro@nvidia.com>
Signed-off-by: Nicolas Morey <nmorey@suse.com>