tests/test_mr.py: Change the argument of DmaBufMR to fix the TypeError
Replaced the argument 'unit' with 'gpu' to fix following error for the DmaBufMRTest:

TypeError: __init__() got an unexpected keyword argument 'unit'

Fixed: ffa97cb59f82 ("tests: Let PyverbsAPITestCase have one default device")
Signed-off-by: Wei Xu <xuwei5@hisilicon.com>