infiniband-diags: Fix a CONSTANT_EXPRESSION_RESULT issue
[ Upstream commit 9768181189130f54b25f9ef7142efc31262952f0 ]

CHECK_AND_SET_VAL((p->qos_class << 4), 16, -1, qos_class, PR, QOS_CLASS);

This Macro is expanded as following lines:

if ((int16_t) (p->qos_class << 4) != (int16_t) -1) {
	qos_class = htobe16((uint16_t) (p->qos_class << 4));
	comp_mask |= IB_PR_COMPMASK_QOS_CLASS;
};

Error: CONSTANT_EXPRESSION_RESULT (CWE-569):
rdma-core-28.0/infiniband-diags/saquery.c:1062: result_independent_of_operands: "(int16_t)(p->qos_class << 4) != -1 /* (int16_t)-1 */" is always true regardless of the values of its operands. This occurs as the logical operand of "if".
|# 1060|     CHECK_AND_SET_VAL(p->pkey, 16, 0, pr.pkey, PR, PKEY);
|# 1061|     CHECK_AND_SET_VAL(p->sl, 16, -1, pr.qos_class_sl, PR, SL);
|# 1062|->   CHECK_AND_SET_VAL((p->qos_class << 4), 16, -1, qos_class, PR, QOS_CLASS);
|# 1063|     pr.qos_class_sl = (pr.qos_class_sl & htobe16(IB_PATH_REC_SL_MASK)) |
|# 1064|               qos_class;

Fixes: 0005d2a088d1 ("saquery.c: Fix changing qos_class flag value to network order twice")
Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>