rstream.c: fix RESOURCE_LEAK issues
[ Upstream commit 5c9647a4234c88921a5358402dc69958fbd614d6 ]

Error: RESOURCE_LEAK (CWE-772):
rdma-core-29.0/librdmacm/examples/rstream.c:410: alloc_arg: "getaddrinfo" allocates memory that is stored into "ai".
rdma-core-29.0/librdmacm/examples/rstream.c:428: leaked_storage: Variable "ai" going out of scope leaks the storage it points to.
|#  426|   		if (ret) {
|#  427|   			printf("getaddrinfo src_addr: %s\n", gai_strerror(ret));
|#  428|-> 			return ret;
|#  429|   		}
|#  430|   	}

Error: RESOURCE_LEAK (CWE-772):
rdma-core-29.0/librdmacm/examples/rstream.c:424: alloc_arg: "getaddrinfo" allocates memory that is stored into "ai_src".
rdma-core-29.0/librdmacm/examples/rstream.c:494: leaked_storage: Variable "ai_src" going out of scope leaks the storage it points to.
|#  492|   	else
|#  493|   		freeaddrinfo(ai);
|#  494|-> 	return ret;
|#  495|   }
|#  496|
Signed-off-by: Honggang Li <honli@redhat.com>

Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>